name: tracer-radar-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.9
  - arm_pyart
  - act-atmos
  - matplotlib
  - jupyterlab
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas
  - fiona
  - imageio
  - metpy
  - geopandas
  - pip
  - pip:
    - -r doc-requirements.txt
    - nexradaws
